### PR TITLE
feat/fix: skip backtracking when far behind, accept pubsub events after idle

### PR DESCRIPTION
**Pull request by leviramsey**
References #95

Will need to add a test for pubsub after idle.

### CODE REVIEW

**Review by patriknw — COMMENTED** [review]
Looking good. This is a port of https://github.com/akka/akka-persistence-r2dbc/pull/614. Anything that is different or that we should watch out for compared to that PR?

**Comment by leviramsey** [comment]
The heartbeat-per-slice is perhaps what I'm most uncertain of (especially wrt to pubsub... maybe it makes sense with this to move pubsub to per-slice (merge slices after pubsub) and default the pubsub topics to 1024?), since R2DBC is heartbeat per slice-range.

**Comment by leviramsey** [comment]
I think the link validator is expected (or is another PR)?

**Review by shawndowns — APPROVED** [review]
lgtm

**Review by patriknw — APPROVED** [review]
LGTM

**Pull request merged**
