### PR TITLE
chore: bump to akka 2.10.0-M1 (#83)

### PR DESCRIPTION
**Pull request by sebastian-alfers**
Came initially from my private fork.

### CODE REVIEW

**Comment by patriknw** [comment]
Thanks for preparing this. We might have to cut some more releases before bumping to the license check, so I'd prefer to not branch. Let's keep this as draft for now.

**Comment by patriknw** [comment]
> license check

well, 2.10.0-M1 is without license check, but we need to stay on stable releases at the moment

**Comment by pvlugter** [comment]
We're considering the dynamodb plugin stable and ready for release. Need this bump for moving projections. Will merge and release a `0.5.0-M1` for now, so that it can be a dependency during the transition.

**Review by pvlugter — APPROVED** [review]
Ignoring link validator.

**Pull request merged**
